import { locale } from "./lib/locale/locale";

export * from "./lib/bug-workarounds/bug-card-holder-assignment";
export * from "./lib/bug-workarounds/bug-unique-cards";
export * from "./lib/card-util/card-util";
export * from "./lib/context-menu/leave-seat";
export * from "./lib/data-store/data-store";
export * from "./lib/dice-group/dice-group";
export * from "./lib/error-handler/error-handler";
export * from "./lib/event/on-card-became-singleton-or-deck";
export * from "./lib/event/triggerable-multicast-delegate";
export * from "./lib/facing/facing";
export * from "./lib/find/find";
export * from "./lib/game-object/cardholder-player-name/cardholder-player-name";
export * from "./lib/game-object/garbage/garbage-container";
export * from "./lib/game-object/garbage/simple-card-garbage-handler";
export * from "./lib/game-object/garbage/simple-to-container-handler";
export * from "./lib/game-object/garbage/simple-to-snap-point-handler";
export * from "./lib/global/abstract-global";
export * from "./lib/layout-objects/layout-objects";
export * from "./lib/locale/locale";
export * from "./lib/nsid/nsid";
export * from "./lib/parse/parse-color";
export * from "./lib/setup/abstract-setup";
export * from "./lib/shuffle/shuffle";
export * from "./lib/spawn/spawn";
export * from "./lib/turn-order/turn-order";
export * from "./lib/widget/confirm-button/confirm-button";
export * from "./lib/widget/d6widget/d6widget";
export * from "./lib/widget/turn-order-widget/turn-clicked-widget";
export * from "./lib/widget/turn-order-widget/turn-entry-wart";
export * from "./lib/widget/turn-order-widget/turn-entry-widget";
export * from "./lib/widget/turn-order-widget/turn-order-widget";

import { DICT } from "./locale.data";
locale.inject(DICT);
